springbootwebfluxjjwt:
  jjwt:
    secret: 'b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBW9nE/cs
WVZ18pX1bk7Yg3AAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQC1f31Amuic
ciDt2AHKcsFlAklgCX3TSPDEM0B0YzIErRw67IX8L+VP0RmX+D7q+4/qj0cDMUD3kcSAky
zoLqNYqAu74TCAvlkJ5RL9ogvB8WbZUC30vDWI/I0xxkQuzDDa7dMvESjESf7KvccFO42S
ZVBWzp3mTIB6D4HHWgSKJprCkEgZzi+UbpG7Bwh9okIKIhCT7d5I2/vgkw3J2hJWkePK9z
HeqrUdsXODlJKBF3OFOusC/5k4UOftvqbMpdh8TbP8hHesgXkM9RDxyhO7O9G0FyfyI/B+
eDfBgzirGD+muwSDz6HYd3a4S3qUV41OUmKFV3LTlmoX+RzI0bGPZN4fpfI8GZ/sPngQiG
asTGjuVUZ8NIa5c1yFMyR/yXcnB9Ua8LW7sO8eWgw63g1WjO75C3o0xze5K7SAfywAGE3U
KiVl4Q+iPh+zEC3q4iNPVCOg8qy0wpf5z9CsR4jGHVi+43vjguFf6VPkpT9NjeM6yeT3IZ
lXXBkHBQoEli6ywbl+s1BypHYbW4Jy7Yj0fYuejR6d6MiwrrrzekQYIpsu+v6g1WKGpJo9
RnkJju7HI4vRJn4jeluaO/OWabO0W9O4fkAJX9xkj+q/0HF3egWym68kD/zEBkfu7gsXXy
Qrd4oWMSlHvf0ayKyi6zJmkuTzCy/VK0bssU2yHS1jrwAAB3C65FaKXoOxkCdBA+IA+uuh
ryzwW+FmLjU+3JlxK5nSlOl0BKfkR6/ArXw6Na5y/6wuEFkmgyeQEdoJG0EnxUU3QBfYig
bV51xAVchwNOWKB1oSmhJIGQ4hvt5V2iTa+84zjlWXgDFcShHUt/rC3j9i3aBi3uQ3Pmux
v62M3N4tI2rq3FuYvWDQfpqLty2SxgCPrec32XDGiSD19JSg9NXaIzXJu26VTFe4k1N6i4
3xm1/MfB6ypUZqP2qlbeA/mmgQPo39vXp2p4dHqWAnnFAhO+S2DbV5W2HTEn6H1aHowKO8
4RmWY8jBSet7UNvZUT5M1NKtIaLlOEVhDBQ26MUgTDH/62bP9HJuRJXbl+jS1pAucMCdVq
6Q6lP3FERMpLTEH/9XQf5/Ve+baNcQN+cgXmXGuiKyB4V1P0zl5AhJldDLnAGqvBRBqAVr
T/Cln4Fwt/oIAlg62HfEoBsywo3jb/huP5gfAESFQn3/CIcm+rAvrbwKt5HSpSGOtgpgMt
IfOhSVlwardg24B7T9JzGBv4DE+Qkzs8r+tRSu2aFXgwOMvO+olwZjMXuKDCCHAbWXYEw9
g7rckatAcS8EVvWW8XCyalR51DBshPbaoEd8Q9F0nvi9YDjMiNQ4N4jTdUVFcG9/ucwlJw
DIw9hstPw2Z+9mmy+PpgwKY2eqiwDIVSEsAgEz8ZuJS/8xc3fqLL+R+xSUE1c6BUzWpfA6
9q/mmpyvuOY/7nZlCOMkenbVOeMaxZ0ijz86Y6IoEHdvg978BaAOt5aaHBLYQfaup/32da
oMn2KymqvA7mbcuJthbsdAR4htZG1UNxhH5qW3awcajBtkmD8HAYFxjaBKsvffAOxOJb6R
2KemwSjK5B3ooUbCf/ow9lpRSCV4KJzD6WVUsf2RK8XK5nk+Zg0FpYbGxDyJSTaLKJ87w2
7ZJt4A21CzyaucZfLrfRh9ciKC7xCk1oNJ2/2OIk66PWt0Rvp4rQhjoKMaPLCEh30c/1XD
45ZOFQV9gYb2KWJ6FA3OXZ9/SwBy5wzH7AAE+8SHtdR09QIENX6ApglPMlhe3iouiwqiXY
LLHyAVio+jVbWbXsC9JuUQyv/z87lvDSGHULXBl4Cue9N3GOnEuAoAP/lBgywdwhbxUbbW
jLfRf4APALy3+j8hREQYkqYUccFBfxLuxUTytBoBPvirq7/cZ6dv8RUHDGhQZrjCekO8Vb
Z/XcWBrP5NXyBJjPqzIOqQzoZoo+roOSeW1ICIJPxGgcPvLPLQevZ3XhbjnSOTzrg4f0Eq
rCU5O0a0Ug8l7SkSea+ROYZ2Jpsrij77ruT8NUrCdA698+Q2fNnK9c2fp6iqRKeZpPn4GO
uFmbxp8EVHOC9HzdBj+VK+e7mb0Cd8N0lm4PROkNvjIrK5RFRKzJz8RgD609PCyTfmURVY
13xoVLRxh8BR/d9Xp4oicIH1CyM7K3h+t/2NjOwnjnOwyRxQfDck4JSCAqGsQYU4cW2B/f
n9rz51VuTVazW8DPloLlUNCmH9tX64ePIr23vzJm7JyaN71KDz56h0M+a1b2/6oBHFeaWQ
xt/7w//vmBPLEf3nCaJNvSaHLZG3DiJFoF0OqBkwuFRn2KEO0xhaJHcPXCEARgthgaaVCF
hLsI/LDqpf6yvkJXg6B7JuxY2K4gwzo9IbHDQXIu0a/NPM+iTIdc5GXMjoTwUrzXcSXb1y
qzexyjMJXA+EbfmDnF0AlwVD1Z4n87eGj8TneXGEa0F02q5p+2h+IUG7n+2e8oWdPYuBo7
xwV9P6AwMIfVcVxQ5kU5CzrwpGbF0lQjkSjELqdOSxb+9OutDsXieAKUK3VvAO03lHbx++
q95M7UP2LmY1SZz+rTrWgXQtPhkePyHnT2iJeLBRZr2/jWdlejQ1ra8sygoJOrlGZIVWgT
bPxpdlkg0T/vS17E+duJ4Uj6o4ZIvHDE/ITz8uv9mhSyzzGg5pQDZPD/b+kNsvPxj2D0wG
CN2rBlHP1oVj5k1sKUKSMyzasSbT41svdsdrueMP7VFYs41zm1xHdSNGIKuq1UN/6KxFxM
wxHOWd9KuCjK7iCajti7hzQ0gXd93gchKQ5E3oE13xhI6Fp6fj0bqnk9W8aV99FkuNzGQK
d5p0nCQZA1hJhRMBaxl3DvpVpI11NWi5Q69OXywKm4Ct3qHc7Ry5FbLE/SmxZMkE6wxE6d
1L936tSJ7DJZAjkrkCVOf3ediiCrVFtWUZL9i5rxNn9eviLRdj/2pzRr9bogaQttQF3W9L
KFlWQXxWga8bev+Sd7kqXB+vM4V22PO212rfcsKI61o6KBKhTcM1jZaQp9z4ZKzu8you5U
qqbKSpaZj9DRBfyA0T/EArkGCLUAN4LwoMjj0uGiHH6mg9hRxFae3IZDVHJLQymfqqE023
5enat0JBwJHPiKgMfFRLnCjp+ob2TLagWZwSjvvx/o4EFYTPx/iEQKE58FvYzg+Ir2K/B6
R9zjsxZce/Cyls6Oan9Yn+s6oZ1fqXSlRBoaPgNcL7497/7vmm7NYchbPFKm4nIKLKuQ==
'
    expiration: 60000


logging:
  level:
    root: debug